Products/urls.py
from django.urls import path
from . import views

app_name = 'Products'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='newpage'),
    path('customer/', views.customer, name='customer'),


]

pyshoup/urls.py
from django.contrib import admin
from django.urls import path
# products
from Products import views


# dprojx/urls.py
from django.conf.urls import url, include
from resit import views
# pyshoup views
from . import views


urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('products/', include('Products.urls')),
    path('resit/', include('resit.urls')),
    #     url(r'^$', views.Loginindex, name='Loginindex'),
    #     url(r'^special/', views.special, name='special'),
    #     url(r'^logout/$', views.user_logout, name='logout'),
    # ]

    # urlpatterns = [
    #     path('admin/', admin.site.urls),
]

resit/urls.py
# dappx/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
# SET THE NAMESPACE!
app_name = 'resit'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    path('', views.Index, name='Index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout', views.user_logout, name='user_logout'),

]

Products/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField()
    stock = models.IntegerField()
    image_url = models.CharField(max_length=2083)


class Offer(models.Model):
    code = models.CharField(max_length=25)
    description = models.CharField(max_length=300)
    discount = models.FloatField()


class Customer(models.Model):
    username = models.CharField(max_length=255)

resit/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

resit/forms.py
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'password', 'email')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

Products/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Product


def index(request):
    products = Product.objects.all()
    return render(request, 'products/dashboard.html', {'items': products})



def new(request):
    return render(request, 'products/new.html')


def customer(request):
    return render(request, 'products/customer.html')

pyshoup/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

resit/views.py
from django.shortcuts import render
from resit.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def Index(request):
    return render(request, 'resit/Loginindex.html')


@login_required
def special(request):
    return HttpResponse("You are logged in !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('resit:Index'))


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'resit/registration.html',
                  {'user_form': user_form,
                           'profile_form': profile_form,
                           'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('resit:Index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(
                username, password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'resit/login.html', {})

templates/home.html
{% extends 'products/base.html' %}

{% block content %}
    {% include 'products/navbar.html' %}

    <p>DashBoard Shamboo Shivaay</p>

    <h1>Products</h1>
   

    
    <!-- <ul>

        <li>{{ product.name }} (Rs. {{ product.price }} per piece)</li>
        {% comment %} {% endfor %} {% endcomment %}
    </ul> -->




{% endblock  %}

templates/products/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- <link rel="stylesheet" href="{% load static %}"> -->


    <title>ProductsHome</title>
</head>

<body>

    <h1>Pyshop</h1>

    {% comment %} {%include 'products/navbar.html'%} {% endcomment %}
    <div class="container">

        {% block content  %}

        {% endblock  %}


    </div>

    <hr>
    <h5>Footer</h5>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>

</body>

</html>

templates/products/cardbase.html
{% extends 'products/base.html' %}
    <!-- Required meta tags -->
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    {% comment %} <title>Card Block!</title> {% endcomment %}
  
  <body>
    {% block contentCard %}
    
    {% endblock %}
    <h1>Products</h1>
    <ul>
        {% for product in items %}
            <li>{{ product.name }} (Rs. {{ product.price }} per piece)</li>
        {% endfor %}
    </ul>

    <!-- Optioncript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>

templates/products/customer.html
{% extends 'products/base.html' %}

{% block content %}
    
    <p>Customer Shamboo</p>

{% endblock  %}

templates/products/dashboard.html
{% extends 'products/base.html' %}

{% block content %}
    <p>DashBoard Shamboo Shivaay</p>

    <h1>Products</h1>
    <div class="row">
        {% for product in items %}
        <div class="col">
            <div class="card" style="width: 18rem;">
                <img src="{{ product.image_url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">Rs {{product.price}}</p>
                    <a href="#" class="btn btn-primary">Add to Cart</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    
    <!-- <ul>

        <li>{{ product.name }} (Rs. {{ product.price }} per piece)</li>
        {% comment %} {% endfor %} {% endcomment %}
    </ul> -->




{% endblock  %}

templates/products/dianov/accounts/customerdianov.html
{%  extends 'accounts/main.html' %}

{% block content %}

	<br>

<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<h5>Customer:</h5>
			<hr>
			<a class="btn btn-outline-info  btn-sm btn-block" href="">Update Customer</a>
			<a class="btn btn-outline-danger  btn-sm btn-block" href="">Delete Customer</a>

		</div>
	</div>

	<div class="col-md">
		<div class="card card-body">
			<h5>Contact Information</h5>
			<hr>
			<p>Email: </p>
			<p>Phone: </p>
		</div>
	</div>

	<div class="col-md">
		<div class="card card-body">
			<h5>Total Orders</h5>
			<hr>
			<h1 style="text-align: center;padding: 10px"></h1>
		</div>
	</div>
</div>


<br>
<div class="row">
	<div class="col">
		<div class="card card-body">
			<form method="get">

		    <button class="btn btn-primary" type="submit">Search</button>
		  </form>
		</div>
	</div>
	
</div>
<br>

<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<table class="table table-sm">
				<tr>
					<th>Product</th>
					<th>Category</th>
					<th>Date Orderd</th>
					<th>Status</th>
					<th>Update</th>
					<th>Remove</th>
				</tr>

			</table>
		</div>
	</div>
</div>

{% endblock %}

templates/products/dianov/accounts/dashboarddianov.html
{%  extends 'products/dianov/accounts/maind.html' %}

{% block content %}

{%  include 'products/dianov/accounts/statusd.html' %}

<br>

<div class="row">
	<div class="col-md-5">
		<h5>CUSTOMERS:</h5>
		<hr>
		<div class="card card-body">
			<a class="btn btn-primary  btn-sm btn-block" href="">Create Customer</a>
			<table class="table table-sm">
				<tr>
					<th></th>
					<th>Customer</th>
					<th>Orders</th>
				</tr>

			</table>
		</div>
	</div>

	<div class="col-md-7">
		<h5>LAST 5 ORDERS</h5>
		<hr>
		<div class="card card-body">
			<a class="btn btn-primary  btn-sm btn-block" href="">Create Order</a>
			<table class="table table-sm">
				<tr>
					<th>Product</th>
					<th>Date Orderd</th>
					<th>Status</th>
					<th>Update</th>
					<th>Remove</th>
				</tr>
		
			</table>
		</div>
	</div>

</div>

{% endblock %}

templates/products/dianov/accounts/maind.html
<!DOCTYPE html>
<html>
<head>
	<title>CRM</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


	<style>
		
		#logo{
		}

		body{
			background-color: #ebeff5;
		}


		#total-orders{
			background-color: #4cb4c7;
		}


		#orders-delivered{
			background-color: #7abecc;
		}

		#orders-pending{
			background-color: #7CD1C0;
		}




	</style>
</head>
<body>
	{%  include 'products/dianov/accounts/navbard.html' %}
	<div class="container-fluid">
	{% block content %}



	{% endblock %}
    </div>
	<hr>
	<h5>Our footer</h5>
	
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

templates/products/dianov/accounts/navbard.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Dashboard</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Products</a>
      </li>
    </ul>
  </div>
</nav>

templates/products/dianov/accounts/productsd.html
{%  extends 'accounts/main.html' %}

{% block content %}

		<br>

		<div class="row">
			<div class="col-md">
				<div class="card card-body">
					<h5>Products</h5>
				</div>
				<div class="card card-body">
					<table class="table">
						<tr>
							<th>Product</th>
							<th>Category</th>
							<th>Price</th>
						</tr>
						
					</table>
				</div>
			</div>
			
		</div>

{% endblock content %}

templates/products/dianov/accounts/statusd.html
<br>

<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title">Total Orders</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title"></h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Delivered</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title"></h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Pending</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title"></h3>
			  	</div>
			</div>
		</div>
	</div>
</div>

templates/products/navbar.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


<h1>Navbar</h1>

 <hr>
 
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">
            {# Django Home Link / Admin Link / Register Link#}
            <li><a class="navbar-brand" href="{% url 'resit:Index' %}">PYSHOP</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="{% url 'resit:register' %}">Register</a></li>     
            <li><a class="navbar-link" href="{% url 'Products:index' %}">Products</a></li>     
            {# Some logic on what to display for last item#}
            {% if user.is_authenticated %}
                <li><a href="{% url 'resit:user_logout' %}">Logout</a></li>
            {% else %}
                <li><a class="navbar-link" href="{% url 'resit:user_login' %}">Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/products/new.html
{% extends 'products/base.html' %}

{% block content %}

    <p>New Page Har har Mahadeva</p>

{% endblock  %}

templates/resit/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'resit:Index' %}">PYSHOP</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'resit:register' %}">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'resit:user_logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'resit:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/resit/login.html
{% extends 'resit/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'resit:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

templates/resit/loginindex.html
{% extends "resit/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Pyshop Djungle !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
        <p>This is just a test paragraph i am writing to check the font style</p>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/resit/registration.html
{% extends "resit/base.html" %}
{% load static %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}